'use client'

import type { Conversation } from './types'
import { LANGUAGE_LABEL, TOOL_ACTION_LABEL } from './types'
import { duration } from './utils'

/** Trigger a client-side file download from a string. */
export function downloadText(filename: string, text: string, mime = 'text/plain') {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

/** One conversation rendered as a readable text block (no file side-effect). */
export function transcriptToText(c: Conversation): string {
  const started = new Date(c.startedAt)
  return [
    'MAGPPIE VOICE — CALL TRANSCRIPT',
    '================================',
    `Call ID      : ${c.id}`,
    `Customer     : ${c.customerName} (${c.customerPhone})`,
    `Agent        : ${c.agentName}`,
    `Direction    : ${c.direction}`,
    `Language     : ${LANGUAGE_LABEL[c.language]}`,
    `Started      : ${started.toLocaleString('en-IN')}`,
    `Duration     : ${duration(c.durationSec)}`,
    `Outcome      : ${c.outcome}`,
    `Sentiment    : ${c.sentiment} (${c.sentimentScore}/100)`,
    '',
    'SUMMARY',
    '-------',
    c.summary,
    '',
    'ACTION ITEMS',
    '------------',
    ...c.actionItems.map((a) => `- ${a}`),
    '',
    'TOOLS CALLED',
    '------------',
    ...c.toolCalls.map(
      (t) => `[${duration(t.atSec)}] ${TOOL_ACTION_LABEL[t.action]} — ${t.status.toUpperCase()} · ${t.detail}`,
    ),
    '',
    'TRANSCRIPT',
    '----------',
    ...c.transcript.map((t) => `[${duration(t.atSec)}] ${t.role.toUpperCase()}: ${t.text}`),
  ].join('\n')
}

/** Download many conversations as one combined .txt (respects the caller's filter). */
export function downloadAllTranscripts(list: Conversation[]) {
  const body = list.map(transcriptToText).join('\n\n' + '='.repeat(60) + '\n\n')
  const header = `MAGPPIE VOICE — TRANSCRIPT EXPORT\n${list.length} call(s)\n\n`
  downloadText('magppie-voice-transcripts.txt', header + body)
}

/** Download a CSV index of conversations (one row per call). */
export function downloadCallIndexCsv(list: Conversation[]) {
  const esc = (v: string) => `"${String(v).replace(/"/g, '""')}"`
  const rows = [
    ['Call ID', 'Customer', 'Phone', 'Agent', 'Direction', 'Language', 'Started', 'Duration', 'Outcome', 'Sentiment', 'Score', 'Summary'],
    ...list.map((c) => [
      c.id,
      c.customerName,
      c.customerPhone,
      c.agentName,
      c.direction,
      LANGUAGE_LABEL[c.language],
      new Date(c.startedAt).toLocaleString('en-IN'),
      duration(c.durationSec),
      c.outcome,
      c.sentiment,
      String(c.sentimentScore),
      c.summary,
    ]),
  ]
  const csv = rows.map((r) => r.map(esc).join(',')).join('\n')
  downloadText('magppie-voice-calls.csv', csv, 'text/csv')
}

/** Build a readable .txt transcript for a conversation and download it. */
export function downloadTranscript(c: Conversation) {
  const text = `${transcriptToText(c)}\n\n--- Generated by Magppie Voice console (mock data) ---`
  downloadText(`${c.id}-${c.customerName.replace(/\s+/g, '-')}.txt`, text)
}
